#!/usr/local/bin/perl
#counts frequency of words
#uses for not foreach

#comparator.pl FILEtoCompare FILEtoCompare FILEGold FILEOutParse FILEOutGold


#use warnings;
use autodie;

$file1 = $ARGV[0];
$file2 = $ARGV[1];
$gold = $ARGV[2];
$parse = $ARGV[3];
$goldout = $ARGV[4];

open my $fh1, '<', $file1;
open my $fh2, '<', $file2;
open my $gh, '<', $gold;
open my $fhparse, '>', $parse;
open my $ghout, '>', $goldout;

while(
  defined( my $line1 = <$fh1> and my $line2 = <$fh2> and my $line3 = <$gh>)
){
  chomp $line1;
  chomp $line2;
  chomp $line3;
	@line11 = split(/\s/, $line1); 
	@line22 = split(/\s/, $line2);
        #interpret the line as an array of words
	if($#line11>6 and $#line22>6){
		if($line11[1] eq $line22[1] and $line11[4] eq $line22[4] and $line11[6] eq $line22[6] and $line11[7] eq $line22[7]){
			#print "match:\n $line1\n";
			print $ghout "$line3\n";
			print $fhparse "$line2\n";
			$line_cnt++;
			$match_cnt++;
		}else{
			#print "\n Lines don't match:\n $line1 \n";
			$line_cnt++;
		}
	}else{ 
		$sentence_cnt ++;
		$score += ($match_cnt/$line_cnt);
		#print "Coverage: ".($match_cnt/$line_cnt)." = $match_cnt / $line_cnt\n";
		$match_cnt = 0; $line_cnt = 0;
		print $ghout "\n";
		print $fhparse "\n";
	}
 
 
}
print " Final Score: ".$score/$sentence_cnt." = $score / $sentence_cnt \n";

close $fh1;
close $fh2;